# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e1f12f25e7cf20121a96ddffb9f9bc7b1a4ee172dfa8d1533ac0de08712150df04214a54cdb22884f5a8f519741f629d30c8e5471004be1d22dd0c608fee1f0

test:
  secret_key_base: 53fdcae04615d081c7b0a151e9838198078c51a6d8decc9d57f5654702bed64f5b16a371ea7f9b7f3b669fc276b3b8c2bd5a0564efeaf37a42a1eec083d7adf6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
